name: Push README to Docker Hub
on:
  workflow_dispatch:  
  push:
    branches:
      - main
    paths:
      - "README.md"
jobs:
  push-readme:
    runs-on: ubuntu-latest
    name: Push README to Docker Hub
    steps:
      - name: git checkout
        uses: actions/checkout@v4

      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_HUB_PASSWORD }}
        with:
          destination_container_repo: friendsofshopware/gitpod-shopware-workspace
          provider: dockerhub
          readme_file: 'README.md'
